# Generated by Django 4.1.3 on 2022-11-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('role', models.CharField(choices=[('admin', 'администратор'), ('super-admin', 'супер-администратор'), ('disabled', 'заблокированный')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('card_number', models.CharField(max_length=16)),
                ('time_unbanned', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'ожидает исполнителя'), (1, 'в работе'), (2, 'готова, но НЕ проверена'), (3, 'проверена, но не оплачена'), (4, 'оплачена'), (5, 'исполнитель просрал время'), (6, 'никто не взял задание в срок')], default=0, verbose_name='статус')),
                ('post_link', models.CharField(max_length=2000, verbose_name='ссылка на пост')),
                ('planned_time', models.DateTimeField(verbose_name='время, когда должно быть исполнено')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('feedback_content', models.TextField(blank=True, default='', verbose_name='содержимое отзыва')),
                ('accepted_time', models.DateTimeField(null=True)),
                ('execution_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='плата исполнителю')),
                ('_order_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена заказа')),
                ('_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания задания')),
                ('_note', models.TextField(verbose_name='примечание')),
                ('_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.admin')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.executor')),
            ],
        ),
    ]
