# Generated by Django 4.1.3 on 2022-11-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('admin', 'администратор'), ('super-admin', 'супер-администратор'), ('disabled', 'заблокированный')], default='admin', max_length=20),
        ),
    ]
