# Generated by Django 4.1.3 on 2022-11-27 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executed_time',
            field=models.DateTimeField(null=True, verbose_name='время, когда было исполнено'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\d{16}')]),
        ),
        migrations.AlterField(
            model_name='executor',
            name='time_unbanned',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
