# Generated by Django 4.1.3 on 2022-11-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_executor_accounts_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='time_unbanned',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='_note',
            field=models.TextField(blank=True, verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='_order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='цена заказа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='executed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время, когда было исполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='db.executor'),
        ),
    ]
