# Generated by Django 4.1.3 on 2022-11-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_executor_time_unbanned_alter_task__note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='card_number',
        ),
        migrations.AddField(
            model_name='executor',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='short_name',
            field=models.CharField(default='задача', max_length=50, verbose_name='короткое имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='db.admin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ожидает исполнителя'), (1, 'в работе'), (2, 'готова, но НЕ проверена'), (3, 'проверена, но не оплачена'), (4, 'оплачена'), (5, 'исполнитель просрал время'), (6, 'никто не взял задание в срок'), (7, 'работа по задаче отменена')], default=0, verbose_name='статус'),
        ),
    ]
